### ISSUE TITLE
Build success, but application not starting properly (Windows 10)

### ISSUE THREAD

**Issue by Wiitzdu** [conundrumer/audioscope#21]
There's a lot more output on the command line beforehand. The application window opens and then closes immediately. Maybe it's using a bad gl version? Not that I know what gl is.

```
...
Pa_StartStream: waveInStart returned = 0x0.
thread 'main' panicked at 'gl function was not loaded', C:\Users\Dustin\Meine Dateien\Programme\audioscope-master\target\release\build\glium-6a0e6ba530832a0a\out/gl_bindings.rs:2506:13
stack backtrace:
!!   0: std::panicking::begin_panic
   1: glium::version::get_gl_version
   2: glium::version::get_gl_version
   3: glium::context::Context::new
   4: glium::backend::glutin_backend::<impl glium::DisplayBuild for glutin::WindowBuilder>::build_glium_debug
   5: audioscope::display::display
   6: core::ptr::drop_in_place<core::option::Option<std::sync::mpsc::stream::Message<()>>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
WinMME StopStream: waiting for background thread.
TerminateHostApis in
TerminateHostApis out
error: process didn't exit successfully: `target\release\audioscope.exe config.toml` (exit code: 101)
```

**Comment by e1ghtSpace** [comment]
Exact same problem here.
```
warning: `audioscope` (bin "audioscope") generated 12 warnings
    Finished release [optimized] target(s) in 0.14s
     Running `target\release\audioscope.exe config.toml`
Default input device name: Microphone (High Definition Aud
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!thread 'main' panicked at 'gl function was not loaded', D:\Downloads\audioscope-master\audioscope-master\target\release\build\glium-694975125115a92e\out/gl_bindings.rs:2506:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\audioscope.exe config.toml` (exit code: 101)
```

**Comment by e1ghtSpace** [comment]
Found a solution.
Just don't compile/run as the release version.

So just use this command:
`cargo run -- config.toml`
